---
title: "Gaussian bayesian networks"
format: html
editor: source
---

```{r}
# Leemos las bases de datos
aire <- read.csv("data/calidad_aire_2025.csv")
sangre <- read.csv("data/ensanut2022_muestras.csv", sep = ";")
socdem <- read.csv("data/ensanut2022_socdem.csv", sep = ";")
```


```{r}
# Columnas con la informacion de los analisis de sangre
biomarcadores <- c("valor_AC_URICO", # Ácido úrico mg/dl
"valor_ALBU", # Albúmina g/dL
"valor_COL_HDL", # Colesterol HDL mg/dl
"valor_COL_LDL", # Colesterol LDL mg/dl
"valor_COLEST", # Colesterol total mg/dl
"valor_CREAT", # Creatinina mg/dl
"valor_GLU_SUERO", # Glucosa mg/dl
"valor_INSULINA", # Insulina micro UI/ml
"valor_PCR", # Proteína C Reactiva mg/dL
"valor_TRIG", # Triglicéridos mg/dl
"valor_EAG", # Glucosa Promedio Estimada mg/dL
"valor_HB1AC", # Hemoglobina glucosilada. %
"valor_FERRITINA", # Ferritina ng/mL
"valor_FOL", # Folato ng/mL
"valor_HCST", # Homocisteina micromol/L
"valor_PROTCREAC", # Proteína C Reactiva mg/L
"valor_STFR_FEB23", # Receptor de Transferrina mg/L
"valor_VIT_B12", # Vitamina B12 pg/mL
"valor_VIT_D", # Vitamina D ng/mL
"ponde_v") # ponderador venosa 20+

# Seleccionar las columnas junto a los ID
sangre_filtered <- sangre[c("FOLIO_I", "FOLIO_INT", biomarcadores)]
```

