---
title: "DAG contaminación ambiental"
format: html
---

```{r}
library(tidyverse)
library(bnlearn)
library(mgcv)
library(gratia)
library(ggplot2)
library(Rgraphviz)

data = read.csv("../data/data.csv")
data[] <- lapply(data, as.numeric)
head(data)
```

## Propuesta de modelo 1: Dra. Aleydis

#### Generar DAG

```{r}
dag1 = model2network("[suma_so_2][suma_co][suma_n_ox][suma_cov][suma_pm_010][suma_pm_2_5][suma_nh_3][pcr|suma_so_2:suma_co:suma_n_ox:suma_cov:suma_pm_010:suma_pm_2_5:suma_nh_3][ac_urico|suma_pm_2_5:suma_pm_010:suma_nh_3][creat|suma_pm_2_5:suma_pm_010:suma_nh_3]")
data_dag1 <- data[, nodes(dag1)]
graphviz.plot(dag1, shape = "ellipse")
```

#### Ajustar datos

```{r}
dag1_fit = bn.fit(dag1, data=data_dag1)

mod_so_2 = lm(suma_so_2 ~ 1, data=data_dag1)
mod_co = lm(suma_co ~ 1, data=data_dag1)
mod_nox = lm(suma_n_ox ~ 1, data=data_dag1)
mod_cov = lm(suma_cov ~ 1, data=data_dag1)
mod_pm_010 = lm(suma_pm_010 ~ 1, data=data_dag1)
mod_pm_2_5 = lm(suma_pm_2_5 ~ 1, data=data_dag1)
mod_nh_3 = lm(suma_nh_3 ~ 1, data=data_dag1)

mod_gam_pcr = gam(pcr ~ s(suma_so_2) + s(suma_co) + s(suma_n_ox) + s(suma_cov) + s(suma_pm_2_5) + s(suma_pm_010) + s(suma_nh_3), data=data_dag1, method="REML")
mod_gam_ac_urico = gam(ac_urico ~ s(suma_pm_2_5) + s(suma_pm_010) + s(suma_nh_3), data=data_dag1, method="REML")
mod_gam_creat = gam(creat ~ s(suma_pm_2_5) + s(suma_pm_010) + s(suma_nh_3), data=data_dag1, method="REML")
```

#### BIC

```{r}
-1/2*(BIC(mod_so_2) + BIC(mod_co) + BIC(mod_nox) + BIC(mod_cov) + BIC(mod_pm_010) +
        BIC(mod_pm_2_5) + BIC(mod_nh_3) + BIC(mod_gam_pcr) + BIC(mod_gam_ac_urico) +
        BIC(mod_gam_creat))
```
```{r}
(AIC(mod_so_2) + AIC(mod_co) + AIC(mod_nox) + AIC(mod_cov) + AIC(mod_pm_010) +
        AIC(mod_pm_2_5) + AIC(mod_nh_3) + AIC(mod_gam_pcr) + AIC(mod_gam_ac_urico) +
        AIC(mod_gam_creat))
```

## Propuesta 2: Dra. Silvia Rodríguez, Dr. Ricardo Cano

#### Generar DAG

```{r}
dag2 = model2network("[suma_so_2][suma_n_ox][suma_pm_010][suma_pm_2_5][suma_nh_3][edad][pcr|suma_so_2:suma_n_ox:suma_pm_010:suma_pm_2_5:suma_nh_3:edad][ac_urico|suma_so_2:suma_n_ox:suma_pm_010:suma_pm_2_5:suma_nh_3:edad][ferritina|suma_so_2:suma_n_ox:suma_pm_010:suma_pm_2_5:suma_nh_3:edad]")
data_dag2 <- data[, nodes(dag2)]
graphviz.plot(dag2, shape = "ellipse")
```

#### Ajustar datos

```{r}
dag2_fit = bn.fit(dag2, data=data_dag2)

mod_so_2 = lm(suma_so_2 ~ 1, data=data_dag2)
mod_nox = lm(suma_n_ox ~ 1, data=data_dag2)
mod_pm_0_10 = lm(suma_pm_010 ~ 1, data=data_dag2)
mod_pm_2_5 = lm(suma_pm_2_5 ~ 1, data=data_dag2)
mod_nh_3 = lm(suma_nh_3 ~ 1, data=data_dag2)

mod_gam_pcr = gam(pcr ~ s(suma_so_2) + s(suma_n_ox) + s(suma_pm_2_5) + s(suma_pm_010) + s(suma_nh_3), data=data, method="REML")
mod_gam_ac_urico = gam(ac_urico ~ s(suma_so_2) + s(suma_n_ox) + s(suma_pm_2_5) + s(suma_pm_010) + s(suma_nh_3), data=data_dag2, method="REML")
mod_gam_ferritina = gam(ferritina ~ s(suma_so_2) + s(suma_n_ox) + s(suma_pm_2_5) + s(suma_pm_010) + s(suma_nh_3), data=data_dag2, method="REML")
```

#### BIC

```{r}
-1/2*(BIC(mod_so_2) + BIC(mod_nox) + BIC(mod_pm_0_10) + BIC(mod_pm_2_5) +
        BIC(mod_nh_3) + BIC(mod_gam_pcr) + BIC(mod_gam_ac_urico) +
        BIC(mod_gam_ferritina))
```

```{r}
(AIC(mod_so_2) + AIC(mod_nox) + AIC(mod_pm_0_10) + AIC(mod_pm_2_5) +
        AIC(mod_nh_3) + AIC(mod_gam_pcr) + AIC(mod_gam_ac_urico) +
        AIC(mod_gam_ferritina))
```


### Super DAG
```{r}
nodos <- c("suma_co","suma_n_ox","suma_so_2","suma_cov","suma_nh_3","suma_pm_010","suma_pm_2_5",
           "pcr","glu_suero","hb1ac","eag","insulina","vit_d","vit_b12","creat",
           "ac_urico","hcst","ferritina","trig","col_hdl","col_ldl","colest","albu")


dag <- empty.graph(nodos)


arcos <- matrix(c(
  
  "suma_co","pcr",
  "suma_n_ox","pcr",
  "suma_so_2","pcr",
  "suma_cov","pcr",
  "suma_nh_3","pcr",
  "suma_pm_010","pcr",
  "suma_pm_2_5","pcr",
  
  
  "pcr","glu_suero",
  
  
  "glu_suero","hb1ac",
  "hb1ac","eag",
  "glu_suero","insulina",
  "glu_suero","vit_d",
  "vit_d","vit_b12",
  "vit_d","creat",
  "creat","ac_urico",
  "eag","ac_urico",
  "glu_suero","hcst",
  "hcst","ferritina",
  
  
  "pcr","trig",
  "suma_pm_010","trig",
  "suma_pm_2_5","trig",
  "trig","col_hdl",
  "trig","col_ldl",
  "col_ldl","colest",
  "trig","albu"
), byrow=TRUE, ncol=2)


arcs(dag) <- arcos


graphviz.plot(dag, shape = "ellipse")
```